site_name: Iris Pie

theme:
    name: material
    font:
        text: Work Sans
        code: Sometype Mono
    palette:
        scheme: slate
        primary: blue grey
        accent: "amber"
    features:
        - navigation.tabs
        - navigation.indexes
        - navigation.top
        - search.suggest
        - content.code.copy
        - content.code.select
    icon:
        logo: iris0
    favicon: favicon/iris0.png
    custom_dir: custom

docs_dir: docs
repo_url: https://github.com/iris-solutions-team/irispie
repo_name: iris-solutions-team/irispie

use_directory_urls: false

extra_css:
    - stylesheets/extra.css

extra:
    site_tagline: Reference Manual

plugins:
    - search
    - awesome-pages

markdown_extensions:
  pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  pymdownx.inlinehilite: {}
  pymdownx.snippets: {}
  pymdownx.superfences: {}
  pymdownx.mark: {}
  admonition: {}
  pymdownx.details: {}
  attr_list: {}
  pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  md_in_html: {}
  footnotes: {}
  pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

